[tool.ruff]
line-length = 88

[tool.ruff.lint]
# I - isort, B - flake8-bugbear, C4 - flake8-comprehensions, SIM - flake8-simplify
extend-select = ["I", "B", "C4", "SIM"]
ignore = ["SIM115", "SIM105"]

[tool.ruff.format]
# black-like style formatter
quote-style = "double"
indent-style = "space"
docstring-code-format = true
