[tox]
envlist = min,py{310,311,312,313}
minversion = 1.7.0
skip_missing_interpreters = True

[test-requirements]
deps =
    pytest==8.1.1
    pytest-cov
    pytest-mock

[testenv]
deps =
    {[test-requirements]deps}
    spidermon
commands = pytest -s --cov=zyte_spidermon --cov-report= {posargs:tests}

[testenv:min]
basepython = python3.10
deps =
    {[test-requirements]deps}
    spidermon==1.18.0
    scrapy==2.6.0
