[tox]
envlist = min,py39,py310,py311,py312,py313
skip_missing_interpreters = True

[testenv]
deps =
    spidermon
    pytest==8.1.1
    pytest-cov
    pytest-mock
extras =
    monitoring
commands = pytest -s --cov=zyte_spidermon --cov-report= {posargs:tests}

[testenv:min]
basepython = python3.9
deps =
    spidermon==1.18.0
    scrapy==2.6.0
    pytest==8.1.1
    pytest-cov
    pytest-mock
extras =
    monitoring
